services:
  - type: web
    name: real-estate-api
    runtime: docker
    dockerfilePath: ./backend/dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://real-eastate-project-gules.vercel.app
